name: Deploy to ECS

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 002332699253.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY_BACKEND: infraalert_backend
  ECR_REPOSITORY_FRONTEND: infraalert_frontend
  ECS_CLUSTER: infraalert-cluster
  ECS_SERVICE: installer-app-service-n1yfiyko

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push backend
        run: |
          docker build --no-cache -t ${{ env.ECR_REPOSITORY_BACKEND }} ./backend
          docker tag ${{ env.ECR_REPOSITORY_BACKEND }}:latest ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_BACKEND }}:latest
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_BACKEND }}:latest

      - name: Build, tag, and push frontend
        run: |
          docker build --no-cache --build-arg NEXT_PUBLIC_API_URL="http://LoadBalancerRael-1878769577.us-east-1.elb.amazonaws.com/api" -t ${{ env.ECR_REPOSITORY_FRONTEND }} ./frontend
          docker tag ${{ env.ECR_REPOSITORY_FRONTEND }}:latest ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_FRONTEND }}:latest
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_FRONTEND }}:latest

      - name: Force new deployment
        run: |
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --force-new-deployment --region ${{ env.AWS_REGION }}